### ISSUE TITLE
Response is empty (can't use SERVER method)

### ISSUE THREAD

**Issue by evolutioncyrus** [BeepFelix/csgo-commend-bot#144]
Subj.
![Untitled](https://user-images.githubusercontent.com/57588616/68547042-b9159f80-03fe-11ea-80f0-80d9d50782d0.png)
My config is:
![image](https://user-images.githubusercontent.com/57588616/68547066-e95d3e00-03fe-11ea-9465-59097fc2c82d.png)
Result:
![image](https://user-images.githubusercontent.com/57588616/68547074-fed26800-03fe-11ea-8b58-325aa7368c74.png)

**Comment by BeepFelix** [comment]
Don't use a local server, use an actual community server.

**Comment by evolutioncyrus** [comment]
> Don't use a local server, use an actual community server.

Thanks for the help! But I've saw how another guys can commend on local

**Comment by BeepFelix** [comment]
This is due to an [update on September 20th](../commit/8e07f79c9ea1fcd022eead67c277116041362afa) which added a check for full servers because full servers do not work.

From that point on all servers get checked before being used, this includes local servers. Therefore local servers no longer work as they don't show up in the server browser and can't be checked.
