### ISSUE TITLE
Report bot not actually working?

### ISSUE THREAD

**Issue by bukubuke** [BeepFelix/csgo-commend-bot#21]
Reported a rage hacker 200 + times and he didn't get OW banned, are the reports going through?

**Comment by BeepFelix** [comment]
If he raged then VACNet for sure catched him aswell, the issue is most probably that Overwatch is overfilled. Too many cheaters + Not enough bans = Some slip through.

*[And I mean... this](https://www.reddit.com/r/GlobalOffensive/comments/89qk3l/i_emailed_a_valve_employee_about_csgo_and_got_a/dwtqe94/)*
