### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by cerolcs** [BeepFelix/csgo-commend-bot#26]
![image](https://user-images.githubusercontent.com/35303121/51875392-f61b1480-234b-11e9-871e-e2040971134a.png)

I got this error when I tried to commend with 600 acc, but just 470 worked correctly!

Any solution??

**Comment by cerolcs** [comment]
OK but the account will be able to use like tomorrow? or I lost my acc??

**Comment by BeepFelix** [comment]
You can use it just fine tomorrow.

**Comment by Lines08** [comment]
I have the same problem but no account was used before generated 10k fresh accounts still same error.
steam guard is off & csgo was started one time

**Comment by cerolcs** [comment]
Today I commended another profile again, the error continues but less than yesterday

**Comment by Lazayi** [comment]
This is common when you're using too many CommendsPerChunk. This also occurs when you're commending someone on an account that's either VAC/Game banned. I could be wrong but I also think this happens when you need to verify the email for the account again when logging in. Just try logging into the account that you got the error from manually and see what it says or if it allows you to login just fine. In my opinion just lower the CommendsPerChunk to like 10 or 15 with about 2 to 10 seconds TimeBetweenChunks. Granted it'll be slower but it'll lower the amount of issues you'll run into.
