### ISSUE TITLE
My Accounts got suspended

### ISSUE THREAD

**Issue by 0xE232FE** [BeepFelix/csgo-commend-bot#59]
All Accounts that uses same Domain for Email Address has been suspended. They didn't VAC or Game Ban the Accounts just disabled them and they force me to contact the Steam Support to unlock them. I used this Accounts only for Commend Bot.

But why does steam support unlock this Accounts and tell me its a misstake sorry? WTF Valve???

All Commends I have done were not removed!
All Accounts were connected to Steam and pretend to Play CSGO to get play Hours.
All Accounts have Steam Guard enabled.

Did someone else experienced this?

**Comment by BeepFelix** [comment]
Don't use accounts from an Account Generator, they were all suspended by Valve. That has nothing to do with this commend bot.

>But why does steam support unlock this Accounts and tell me its a misstake sorry? WTF Valve???

Because they simply don't care enough. Nobody is gonna go through 18+ million accounts (total from [SAG](https://accgen.cathook.club/)) and request them to be unlocked.

My 40k accounts have been generated before all the account generator "hype" started so therefore I am fine but I didn't check them all yet and I don't care enough to do so.

---

Regardless as said above not really an issue with the commend bot itself.
