### ISSUE TITLE
Some errors that Ive received and I want to know what it means

### ISSUE THREAD

**Issue by kblade07** [BeepFelix/csgo-commend-bot#77]
Hello dev. Im using this script for like 1 week and its working most of the time. Im using f2p accounts and im using 100 to send, 20/chunk. Out of 20, sometimes 17 are working, sometimes 10 are working, sometimes 5 are working. I let the bots on cooldown for 72 hours and i tested on a smurf and a lot of accounts, like 40 got this error:
```
 [WellmadeDirtyRook19] Failed to commend (11/11) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\alx\\Downloads\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:154:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
```
Id like to know to investigate this issue. What does this mean for the accounts? The account gets logged in but then its goes into this error.

Another error, but I dont see this very often is: Commendation succesful but with invalid code 2. This means that the account already commended the target or that the account is on cooldown?

Also, how to update it via CMD?
```
A new version is available on Github @ https://github.com/BeepFelix/csgo-commend-bot
 Downloading is optional but recommended. Make sure to check if there are any new values to be added in your old "config.json"

```

It still does need to switch the server after 20? Do you think this is a good setting for botting in bulk?

```
"toSend": 151,
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
```

Should I go lower on the perChunk, to 10 maybe, so i wont get the first TimeOut Error? Because I have no idea how to deal with this TimeOut error or what doest it mean

Thank you

**Comment by BeepFelix** [comment]
>What does this mean for the accounts? The account gets logged in but then its goes into this error.

The account successfully logged in, the account successfully established connection to CSGO, the account tried to send a commend to the target but never got a response from CSGO. Meaning it wasn't accepted by CSGO.

>Another error, but I dont see this very often is: Commendation succesful but with invalid code 2

I am unsure what this exactly means, `2` just means `Fail` as per [SteamErrors.com](https://steamerrors.com/). There is no clear description. It *could* mean something like "Already Commended" but I am unsure. Would require testing.

>Also, how to update it via CMD?

If you used [Git](https://git-scm.com/downloads) originally to download the repository just enter `git pull`. Otherwise simply go to the repository, download it again and replace all files. Make sure to **not** delete your `accounts.sqlite` it has crucial information you **100% want to keep**.

Then just check out the `config.json.example` and compare it to your `config.json`, see if there are any new variables missing.

>It still does need to switch the server after 20? Do you think this is a good setting for botting in bulk?

From my testing a few months ago 20 per 5 minutes was working good enough. I don't know what determines if they work or not. You can test around if you want and just change them a lot. Accounts only get marked as "Successfully commended" if CSGO returns success.

**Comment by kblade07** [comment]
Hey, thank you for the reply. I think I found the reason for the first error following your FAQ. You said there that the account cannot receive too many commends in a short period of time. First chunk worked 20/20 but the second one, with a cooldown of just 2 seconds in between the chunks, worked 6/20. All 14 account got the TimeOut error. The second error is related to "already commended" from what I see.
